'use client';
import {useEffect,useState} from 'react';
import {bookingFetch} from '@/lib/booking-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {CalendarDays,ArrowRight,CheckCircle2,Video,MapPin,RefreshCw} from 'lucide-react';
type Slot={slot:string;available:boolean};
export default function Booking(){const [slots,setSlots]=useState<Slot[]>([]),[date,setDate]=useState(''),[slot,setSlot]=useState(''),[mode,setMode]=useState('video'),[name,setName]=useState(''),[consent,setConsent]=useState(false),[loading,setLoading]=useState(true),[preview,setPreview]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<{id:string;slot:string}|null>(null);
async function refresh(){setLoading(true);setError('');try{const r=await bookingFetch();const d=await r.json();if(!r.ok)throw Error(d.error);setSlots(d.slots);setPreview(d.preview===true);setDate(v=>v||d.slots[0]?.slot.slice(0,10)||'');}catch(e){setError(e instanceof Error?e.message:'加载失败');}finally{setLoading(false);}}
useEffect(()=>{refresh();const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'start_booking',description:'打开演示预约区域，供用户选择档期；不会提交预约。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');document.getElementById('booking')?.scrollIntoView({behavior:'smooth'});return {status:'booking_form_opened'};}},{signal:lifecycle.signal});}catch{}return ()=>lifecycle.abort();},[]);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await bookingFetch({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,slot,mode,consent})});const d=await r.json();if(!r.ok){if(r.status===409){setSlot('');await refresh();}throw Error(d.error);}setReceipt(d);}catch(e){setError(e instanceof Error?e.message:'网络异常，请重试');}finally{setBusy(false);}}
async function cancel(){if(!receipt)return;setBusy(true);setError('');try{const r=await bookingFetch({method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:receipt.id})});if(!r.ok)throw Error('暂时无法取消，请重试');setReceipt(null);setSlot('');await refresh();}catch(e){setError(e instanceof Error?e.message:'取消失败');}finally{setBusy(false);}}
const dates=[...new Set(slots.map(s=>s.slot.slice(0,10)))];return <section id="booking" className="section booking"><div className="section-heading"><div><div className="eyebrow">MAKE TIME FOR YOURSELF</div><h2>留一段时间，照顾自己。</h2><p className="muted">不需要准备好所有答案，从选择一个时间开始。</p></div><span className="status-dot">{preview?'展示版 · 示例档期':'近期可预约 · 示例档期'}</span></div><div className="booking-grid"><aside className="booking-intro"><CalendarDays size={30}/><h3>你的 50 分钟</h3><p>一个只属于你的、不被打扰的空间。</p><div>个人心理咨询</div><strong>¥ 500 <small>/ 次 · 示例价格</small></strong><hr/><p><Video size={15}/> 线上视频 / 线下面谈</p><p>所有时间均为北京时间（UTC+8）</p><small>本页为功能演示。不会安排真实咨询，也不会扣费或发送通知。请仅填写昵称，不要填写健康或身份信息。</small></aside><div className="booking-form">{receipt?<div className="success"><CheckCircle2 size={40}/><h3>演示预约已保存</h3><p>{receipt.slot.replace('T',' ')} · 50 分钟</p><p>这不是正式咨询确认。你可以保存预约凭证，或在此取消演示预约。</p><Button variant="outline" onClick={()=>{const blob=new Blob([`心屿 · 演示预约\n时间：${receipt.slot}\n预约凭证：${receipt.id}\n本记录不安排真实服务。`],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='心屿演示预约.txt';a.click();URL.revokeObjectURL(url);}}>保存预约凭证</Button> <Button variant="ghost" disabled={busy} onClick={cancel}>取消演示预约</Button></div>:<form onSubmit={submit}><h3>01 <span>选择咨询方式</span></h3><div className="mode-buttons"><Button type="button" variant="outline" aria-pressed={mode==='video'} onClick={()=>setMode('video')}><Video/>线上视频</Button><Button type="button" variant="outline" aria-pressed={mode==='inperson'} onClick={()=>setMode('inperson')}><MapPin/>线下面谈（地点待定）</Button></div><h3>02 <span>选择日期与时间</span></h3>{loading?<p role="status">正在加载档期…</p>:dates.length?<><div className="dates">{dates.map(day=><Button type="button" variant="outline" key={day} aria-pressed={date===day} onClick={()=>{setDate(day);setSlot('');}}><small>{new Date(day+'T12:00:00+08:00').toLocaleDateString('zh-CN',{weekday:'short',timeZone:'Asia/Shanghai'})}</small><b>{day.slice(5).replace('-',' / ')}</b></Button>)}</div><div className="times">{slots.filter(s=>s.slot.startsWith(date)).map(s=><Button type="button" variant="outline" key={s.slot} disabled={!s.available} aria-pressed={slot===s.slot} onClick={()=>setSlot(s.slot)}>{s.slot.slice(11)}{!s.available?' 已约':''}</Button>)}</div></>:<p>暂无可预约档期。</p>}<div className="name-row"><label htmlFor="nickname">如何称呼你？</label><Input id="nickname" placeholder="请填写昵称" value={name} onChange={e=>setName(e.target.value)} maxLength={30} required/></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/>我了解这是演示预约，仅保存昵称、时间与咨询方式，不代表真实服务。</label><Button className="submit" type="submit" disabled={preview||busy||!slot||!consent||!name.trim()}>{preview?'预约尚未开放':busy?'正在保存…':'确认演示预约'}<ArrowRight/></Button></form>}{error&&<div role="alert" className="error">{error} <Button variant="ghost" onClick={refresh}><RefreshCw/>重新加载</Button></div>}</div></div></section>}
