'use client';
import {useState} from 'react';
import {ArrowUpRight,Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const articles=[{category:'自我探索',title:'不着急成为“更好的自己”',sub:'也许此刻的你，就值得被温柔对待。',image:'photo-1441974231531-c6227db76b6e',body:['我们常常把生活写成一份待完成的清单：更自律、更勇敢、更从容。可在忙着赶路的时候，也许可以问自己：这些期待，哪些来自我的愿望，哪些来自别人的目光？','这不是一份要求你改变的练习。你可以为自己留下一页空白，写下最近让你觉得自在的一刻。没有也没关系，今天不需要交出答案。','试着把“我应该”换成“我希望”，看看句子发生了什么变化。你可以保留一个小小的愿望，也可以暂时什么都不决定。']},{category:'情绪觉察',title:'给说不清的感受，一个位置',sub:'不必立刻解释，也可以先听一听。',image:'photo-1470252649378-9c29740c9fa8',body:['有时我们只知道自己不太好，却找不到一个准确的词。此时不妨暂时放下“为什么”，用自己的语言描述今天：像阴天，像一团线，或像一段没有写完的句子。','如果你愿意，可以记下“发生了什么”“我想说什么”“我此刻希望得到什么”。这些文字只属于你，无需写得完整，也不必给它们打分。','如果记录让你不舒服，可以随时停下来。这篇分享只是一个自我观察的邀请，不是诊断，也不替代专业支持。']},{category:'关系与边界',title:'在关系里，为自己留一点空间',sub:'靠近彼此，也不必失去自己。',image:'photo-1447752875215-b2761acb3c5d',body:['“我今天想先休息一下。”这样简单的一句话，有时也很难说出口。我们可能担心让对方失望，或不知道如何表达不同的需要。','可以试着从具体的一件小事开始，把“你总是”换成对当下的描述：“今晚我有点累，我想明天再聊这件事。”这只是表达的一种可能，不保证每段对话都会顺利。','好的边界不必一次说得完美。你可以观察自己的感受，也听听对方的回应，在适合自己的速度里尝试。'] }];
const faqs=[['第一次咨询，需要准备什么？','可以从最近让你在意的一件事说起，不需要事先整理完整经历。正式服务开始前，咨询师应与你说明咨询设置、保密约定与费用，并确认双方是否适合继续合作。'],['不知道怎么表达，也可以来咨询吗？','可以把“不知道从哪里说起”作为开场。咨询中可以停顿，也可以表达不想谈某个话题；你有权按自己的节奏参与。'],['线上与线下咨询有什么区别？','本示例两种方式均为 50 分钟。线上需要安静、私密的空间与稳定网络；线下面谈的实际地址应在正式预约前确认，目前示例地址尚未设置。'],['可以改期或取消吗？','演示预约保存后，可以在确认页取消并释放时段。正式服务的改期、取消及退款规则需由咨询师补充，网站目前不收取任何费用。'],['咨询内容会被保密吗？','正式咨询前应阅读并确认咨询师提供的保密协议及其例外说明。本演示预约只收集昵称、时间与方式，请勿提交个人健康、身份或其他敏感信息。'],['这个网站可以直接预约真实咨询吗？','目前不可以。咨询师、收费和档期均为示例，预约仅用于体验流程，不会发送通知或安排真实服务。真实资料、联系渠道及服务规则确认后，方可用于正式预约。']];
export default function Content(){const [article,setArticle]=useState<number|null>(null);return <><section id="journal" className="section journal"><div className="section-heading"><div><div className="eyebrow">NOTES FOR YOUR INNER WORLD</div><h2>关于内心的一些小事</h2></div><span className="muted">心理学分享 · 给日常一点新的视角</span></div><div className="article-grid">{articles.map((a,i)=><button className="article-card" key={a.title} onClick={()=>setArticle(i)}><div className="article-image"><img src={['./images/forest.jpg','./images/dawn.jpg','./images/trees.jpg'][i]} alt={['绿意盎然的森林','薄雾中的晨光','安静的林间风景'][i]} loading="lazy"/><span>{a.category}</span></div><h3>{a.title}<ArrowUpRight size={18}/></h3><p>{a.sub}</p><small>心屿手记 · 2 分钟阅读</small></button>)}</div></section><section id="process" className="process-wrap"><div className="section"><div className="section-heading"><div><div className="eyebrow">A GENTLE BEGINNING</div><h2>让开始，简单一点。</h2></div><span className="muted">咨询流程与收费</span></div><div className="steps">{[['01','选择档期','找到适合你的日期、时间与咨询方式。'],['02','初步沟通','正式服务中需确认需求、费用及咨询设置。'],['03','开始对话','在约定时间，进入一个专注于你的空间。'],['04','一起回顾','讨论感受与目标，自主决定是否继续。']].map(([n,t,p])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></div>)}</div><div className="price-row"><div><h3>个体心理咨询</h3><p>成年人 · 线上视频 / 线下面谈 · 每次 50 分钟</p></div><strong>¥ 500 <small>/ 次</small></strong><a href="#booking">查看预约档期 <ArrowUpRight size={17}/></a></div><p className="price-note">示例收费，不在线扣费。实际价格、资质、服务范围与取消规则需由咨询师确认。</p></div></section><section id="faq" className="section faq"><div><div className="eyebrow">YOU MAY BE WONDERING</div><h2>你可能还想知道</h2><p className="muted">为未知多一份了解，<br/>让开始少一点顾虑。</p></div><div>{faqs.map(([q,a],i)=><details key={q}><summary><span><small>0{i+1}</small>{q}</span><Plus size={17}/></summary><p>{a}</p></details>)}</div></section><section className="closing"><SproutIcon/><h2>愿你在被理解中，重新遇见自己。</h2><p>当你准备好了，这里有一个可以开始的地方。</p><a className="primary-link" href="#booking">给自己一段时间 <ArrowUpRight size={17}/></a></section><Dialog open={article!==null} onOpenChange={open=>{if(!open)setArticle(null)}}><DialogContent className="reading-dialog">{article!==null&&<><DialogTitle className="reading-title">{articles[article].title}</DialogTitle><DialogDescription>{articles[article].category} · 心屿手记</DialogDescription>{articles[article].body.map(p=><p key={p}>{p}</p>)}<small>本文为一般性自我探索分享，不用于诊断或治疗。</small><Button variant="outline" onClick={()=>setArticle(null)}>读完了，慢慢来</Button></>}</DialogContent></Dialog></>}
function SproutIcon(){return <span className="tiny-sprout">✳</span>}
