import {useEffect,useRef,useState,type ChangeEvent} from 'react';
import {createRoot} from 'react-dom/client';
import {defaultContent,validateContent,sectionNames,formatText,safeLink,type SiteContent} from '@/lib/site';
import './editor.css';

type Path=Array<string|number>;
const groups=Object.keys(defaultContent);
const hints:Record<string,string>={
 品牌:'网站名称、咨询师姓名会自动同步到引用它们的位置。',
 首屏:'在文字框中换行，网页也会跟着换行。图片可选择本地文件或填写图片网址。',
 心理学分享:'文章可新增、删除、排序。展开文章可修改封面、摘要和全部正文；在右侧预览中点击文章卡片，即可预览独立详情页。链接标识决定文章网址，发布后保持不变可以保留旧链接。',
 咨询师简介:'这里可以修改咨询风格与理念。展开“资质背景”可编辑教育、受训、进修和专业支持，也可新增分类、增删项目或隐藏整个背景区域。',
 常见问题:'问题与回答均可修改，也可以新增、删除和排序。',
 版块顺序:'上下移动调整顺序。各版块中的“显示”开关可以隐藏整个版块。',
 外观:'主要颜色、字体、大小与间距可直接修改；细节颜色保留了原设计的所有色值。自定义样式供进一步调整布局使用。',
 档期:'这里修改示例档期。接通预约后台后，以后台档期为准；修改正式档期需要同步更新并部署后台。所有时间均为北京时间。',
 预约服务:'留空时只展示示例档期，不提交预约。只有填入已经部署好的预约后台地址，才会连接保存服务。',
};
function readPath(value:unknown,path:Path):any{return path.reduce<any>((item,key)=>item?.[key],value)}
function setPath(value:SiteContent,path:Path,next:unknown){const copy=structuredClone(value);let parent:any=copy;for(const key of path.slice(0,-1))parent=parent[key];parent[path[path.length-1]]=next;return copy;}
function newItem(template:any,path:Path){const item=blank(template);if(path.join('.')==='心理学分享.文章')item.链接标识='article-'+crypto.randomUUID();return item;}
function blank(template:any):any{if(Array.isArray(template))return template.length?[blank(template[0])]:[];if(template&&typeof template==='object')return Object.fromEntries(Object.entries(template).map(([k,v])=>[k,blank(v)]));if(typeof template==='boolean')return true;if(typeof template==='number')return template;return '';}
function Editor(){
 const [content,setContent]=useState<SiteContent>(structuredClone(defaultContent));
 const [loaded,setLoaded]=useState(false),[dirty,setDirty]=useState(false),[group,setGroup]=useState(groups[0]),[status,setStatus]=useState('正在读取网站内容…'),[error,setError]=useState(''),[mobile,setMobile]=useState(false),[previewVisible,setPreviewVisible]=useState(true),[previewScale,setPreviewScale]=useState(1);
 const original=useRef<SiteContent>(structuredClone(defaultContent)),frame=useRef<HTMLIFrameElement>(null),canvas=useRef<HTMLDivElement>(null),current=useRef(content),importer=useRef<HTMLInputElement>(null);
 current.current=content;
 useEffect(()=>{if(!canvas.current)return;const resize=()=>setPreviewScale(Math.min(1,canvas.current!.clientWidth/(mobile?375:1280)));resize();const observer=new ResizeObserver(resize);observer.observe(canvas.current);return()=>observer.disconnect();},[mobile,previewVisible]);
 const sendPreview=()=>{try{const value=validateContent(current.current);frame.current?.contentWindow?.postMessage({type:'guangdu-preview',content:value},window.location.origin);}catch{/* A partial input may be temporarily invalid. */}};
 useEffect(()=>{
  let active=true;
  fetch('./site-content.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('无法读取已发布的内容，请刷新重试。');return r.json();}).then(value=>{const next=validateContent(value);if(active){original.current=structuredClone(next);setContent(next);setLoaded(true);setStatus('已载入网站内容。修改仅在本页预览，导出并上传后才会发布。');}}).catch(e=>{if(active){setError(e.message);setStatus('已载入随网站附带的默认内容，请确认后再导出。');setLoaded(true);}});
  return()=>{active=false};
 },[]);
 useEffect(()=>{const timer=setTimeout(sendPreview,180);return()=>clearTimeout(timer);},[content,previewVisible]);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin===window.location.origin&&event.source===frame.current?.contentWindow&&event.data?.type==='guangdu-preview-ready')sendPreview();};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[]);
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
 function update(path:Path,value:unknown){setContent(old=>setPath(old,path,value));setDirty(true);setError('');setStatus('有未导出的修改。预览不会改变已发布的网站。');}
 function download(){try{validateContent(content);const blob=new Blob([JSON.stringify(content,null,2)+'\n'],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='site-content.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);setDirty(false);setStatus('已导出 site-content.json。请上传到仓库 docs 文件夹；当前线上网站尚未改变。');}catch(e){setError(e instanceof Error?e.message:'导出失败');}}
 async function importFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw Error('内容文件不能超过 20 MB。');const next=validateContent(JSON.parse(await file.text()));setContent(next);setDirty(true);setError('');setStatus('已导入到预览。导出并上传后才会发布。');}catch(e){setError(e instanceof Error?e.message:'文件格式不正确');}}
 async function importImage(path:Path,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(!/^image\/(png|jpeg|webp|gif|avif)$/.test(file.type))throw Error('请选择 PNG、JPG、WebP、GIF 或 AVIF 图片。');if(file.size>3*1024*1024)throw Error('单张图片请控制在 3 MB 以内。');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('图片读取失败'));reader.readAsDataURL(file);});update(path,data);}catch(e){setError(e instanceof Error?e.message:'图片读取失败');}}
 function field(value:any,path:Path,label:string):React.ReactNode{
  const key=path.join('.'),id='field-'+key;
  if(Array.isArray(value)){
   let example:any=readPath(defaultContent,path.map(k=>typeof k==='number'?0:k));example=Array.isArray(example)?example[0]:'';
   return <fieldset className="editor-list" key={key}><legend>{label} <span>{value.length} 项</span></legend>{value.map((item,i)=><details className="list-item" key={i} open={typeof item!=='object'||undefined}><summary><span>{typeof item==='object'?(item.标题||item.问题||item.文字||`第 ${i+1} 项`):`第 ${i+1} 项`}</span><span className="item-actions"><button type="button" aria-label={`${label}第 ${i+1} 项上移`} disabled={i===0} onClick={event=>{event.preventDefault();const next=[...value];[next[i-1],next[i]]=[next[i],next[i-1]];update(path,next)}}>↑</button><button type="button" aria-label={`${label}第 ${i+1} 项下移`} disabled={i===value.length-1} onClick={event=>{event.preventDefault();const next=[...value];[next[i+1],next[i]]=[next[i],next[i+1]];update(path,next)}}>↓</button><button type="button" onClick={event=>{event.preventDefault();update(path,value.filter((_,index)=>index!==i))}}>删除</button></span></summary>{path[0]==='版块顺序'?<label className="editor-field" htmlFor={id+i}>版块<select id={id+i} value={item} onChange={e=>update([...path,i],e.target.value)}>{sectionNames.map(name=><option key={name} disabled={value.includes(name)&&name!==item}>{name}</option>)}</select></label>:field(item,[...path,i],typeof item==='object'?'内容':label==='段落'?`第 ${i+1} 段`:'内容')}</details>)}<button className="add-button" type="button" disabled={value.length>=100||(path[0]==='版块顺序'&&value.length>=sectionNames.length)} onClick={()=>update(path,[...value,path[0]==='版块顺序'?sectionNames.find(name=>!value.includes(name)):newItem(example,path)])}>＋ 新增{label==='段落'?'段落':'一项'}</button></fieldset>
  }
  if(value!==null&&typeof value==='object')return <div className="object-fields" key={key}>{Object.entries(value).map(([child,item])=>{const nested=item!==null&&typeof item==='object'&&!Array.isArray(item);return nested?<details className="field-group" key={child} open={child!=='细节颜色'}><summary>{child}</summary>{field(item,[...path,child],child)}</details>:field(item,[...path,child],child)})}</div>;
  if(typeof value==='boolean')return <label className="editor-switch" key={key}><span>{label}</span><input type="checkbox" checked={value} onChange={e=>update(path,e.target.checked)}/><span>{value?'显示':'隐藏'}</span></label>;
  if(typeof value==='number')return <label className="editor-field" key={key} htmlFor={id}>{label}<input id={id} type="number" min="1" max="90" value={value} onChange={e=>update(path,Number(e.target.value))}/></label>;
  const isImage=label.endsWith('图片')||label==='网站图标';
  const isColor=path.includes('主要颜色')||path.includes('细节颜色');
  if(isImage)return <div className="editor-field" key={key}><label htmlFor={id}>{label}</label>{value&&<img className="image-preview" src={safeLink(value,true)} alt={`${label}预览`}/>}<input id={id} value={value.startsWith('data:')?'已选择本地图片（随内容文件一起保存）':value} readOnly={value.startsWith('data:')} placeholder="图片网址，或 ./images/文件名.jpg" onChange={e=>update(path,e.target.value)}/><div className="image-actions"><label className="file-button">选择图片<input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif" onChange={e=>importImage(path,e)}/></label><button type="button" onClick={()=>update(path,'')}>清空图片</button></div></div>;
  if(isColor)return <label className="editor-field color-field" key={key} htmlFor={id}>{label}<span><input aria-label={`${label}色盘`} type="color" value={/^#[0-9a-f]{6}$/i.test(value)?value:'#566b43'} onChange={e=>update(path,e.target.value)}/><input id={id} value={value} onChange={e=>update(path,e.target.value)}/></span></label>;
  const multiline=value.includes('\n')||value.length>55||['正文','段落','回答','说明','自定义样式','凭证内容'].some(word=>label.includes(word));
  return <label className="editor-field" key={key} htmlFor={id}>{label}{multiline?<textarea id={id} rows={label==='自定义样式'?9:4} value={value} spellCheck={false} onChange={e=>update(path,e.target.value)}/>:<input id={id} value={value} onChange={e=>update(path,e.target.value)}/>}</label>;
 }
 return <><header className="editor-top"><a href="./" target="_blank" rel="noreferrer" className="editor-brand">{content.品牌.名称} <span>网站编辑</span></a><div><button disabled={!loaded} onClick={()=>importer.current?.click()}>导入内容</button><button disabled={!loaded} onClick={()=>{if(confirm('恢复打开编辑器时的内容？当前修改会被替换。')){setContent(structuredClone(original.current));setDirty(false);setError('');setStatus('已恢复打开编辑器时的内容。')}}}>撤销本次修改</button><button className="editor-primary" disabled={!loaded} onClick={download}>导出修改</button></div><input ref={importer} type="file" accept=".json,application/json" hidden onChange={importFile}/></header><div className="editor-notice"><strong>编辑 → 预览 → 导出 → 上传发布</strong><p>这里是你的编辑工作台。只有将导出的文件上传到 GitHub，访客才会看到修改。无需填写密码或令牌。</p><details><summary>如何发布修改？</summary><ol><li>点击“导出修改”，得到 site-content.json。</li><li>打开 <a href="https://github.com/msdseason/guangdu/upload/main/docs" target="_blank" rel="noreferrer">GitHub 的 docs 文件夹上传页</a>，上传这个文件并提交更改。需要登录仓库所有者账号。</li><li>GitHub Pages 开启后会自动发布。图片选择器导入的图片已经包含在内容文件内，无需额外上传。</li></ol><p>保留文件名 site-content.json。GitHub 若仍未开启 Pages，请在仓库 Settings → Pages 中将 Source 设为 GitHub Actions。</p></details></div><div className="editor-status" role="status">{status}</div>{error&&<div className="editor-error" role="alert">{error}</div>}<div className="editor-layout"><aside className="editor-sidebar" aria-label="编辑分类">{groups.map(name=><button key={name} className={group===name?'active':''} onClick={()=>setGroup(name)}>{name}</button>)}</aside><main className="editor-fields"><h1>{group}</h1><p className="editor-hint">{hints[group]||'文字、按钮和说明均可修改。可以使用下方的自动引用，让多处内容保持一致。'}</p><details className="template-help"><summary>自动引用说明</summary><p>{'{品牌}、{简称}、{咨询师}、{价格}、{时长}、{币种}、{年份} 会显示为品牌和服务设置里的内容。例如“你好，我是{咨询师}。”会显示为“'+formatText(content,'你好，我是{咨询师}。')+'”'}</p></details>{loaded?field(content[group as keyof SiteContent],[group],group):<p>正在读取…</p>}</main><aside className="editor-preview"><div className="preview-toolbar"><strong>即时预览</strong><div><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>电脑</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>手机</button><button onClick={()=>setPreviewVisible(!previewVisible)}>{previewVisible?'隐藏':'显示'}</button></div></div>{previewVisible&&<div ref={canvas} className="preview-canvas"><iframe ref={frame} src="./?preview=1" title="网站修改预览" style={{width:mobile?375:1280,height:650/previewScale,transform:`scale(${previewScale})`}} onLoad={sendPreview}/></div>}<p>预览仅供查看，未发布。<a href="./" target="_blank" rel="noreferrer">打开网站 ↗</a></p></aside></div></>
}
createRoot(document.getElementById('root')!).render(<Editor/>);
